# Generated by Django 5.2.14 on 2026-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_slot_duration', models.IntegerField(default=30, verbose_name='Durée par défaut (min)')),
                ('bookings_paused', models.BooleanField(default=False, verbose_name='Réservations en pause')),
                ('pause_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Motif de pause')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration système',
                'verbose_name_plural': 'Configuration système',
            },
        ),
    ]
