# Generated by Django 5.2.14 on 2026-05-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemconfig'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_resource_exact_booking_slot',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('EN_ATTENTE', 'Paiement en attente'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ANNULE'), _negated=True), fields=('resource', 'booking_date', 'start_time', 'end_time'), name='unique_resource_exact_booking_slot'),
        ),
    ]
