# Generated by Django 5.2.14 on 2026-06-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_booking_unique_resource_exact_booking_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secret_code_plain',
            field=models.CharField(blank=True, default='', help_text='Stocké en clair pour pouvoir réimprimer le ticket client.', max_length=6, verbose_name='Code secret (clair)'),
        ),
    ]
