# Generated by Django 5.2.14 on 2026-06-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_secret_code_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BARIDIMOB', 'BaridiMob')], max_length=20, null=True, verbose_name='Moyen de paiement'),
        ),
    ]
