# Generated by Django 5.2.14 on 2026-06-08 13:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_booking_chargily_checkout_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtablissementMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_specifique', models.DecimalField(blank=True, decimal_places=2, help_text='Surcharge le prix de base pour cet établissement uniquement.', max_digits=10, null=True, verbose_name='Prix spécifique (DA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mode_links', to='api.establishment', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Mode par établissement',
                'verbose_name_plural': 'Modes par établissement',
                'db_table': 'etablissement_mode',
            },
        ),
        migrations.CreateModel(
            name='ModeLavage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, verbose_name='Nom')),
                ('duree', models.PositiveIntegerField(verbose_name='Durée (minutes)')),
                ('prix_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Prix de base (DA)')),
                ('capacite_max', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Capacité max (kg)')),
                ('types_vetements', models.JSONField(blank=True, default=list, help_text='Liste de types de vêtements pris en charge.', verbose_name='Types de vêtements')),
                ('message_guide', models.TextField(blank=True, default='', verbose_name='Message guide')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('etablissements', models.ManyToManyField(blank=True, related_name='modes_lavage', through='api.EtablissementMode', to='api.establishment', verbose_name='Établissements')),
            ],
            options={
                'verbose_name': 'Mode de lavage',
                'verbose_name_plural': 'Modes de lavage',
                'db_table': 'modes_lavage',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='etablissementmode',
            name='mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissement_links', to='api.modelavage', verbose_name='Mode de lavage'),
        ),
        migrations.AddIndex(
            model_name='modelavage',
            index=models.Index(fields=['nom'], name='modes_lavag_nom_1275ab_idx'),
        ),
        migrations.AddIndex(
            model_name='etablissementmode',
            index=models.Index(fields=['etablissement', 'mode'], name='etablisseme_etablis_42ef57_idx'),
        ),
        migrations.AddConstraint(
            model_name='etablissementmode',
            constraint=models.UniqueConstraint(fields=('etablissement', 'mode'), name='unique_etablissement_mode'),
        ),
    ]
