# Generated by Django 5.2.14 on 2026-06-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_etablissementmode_modelavage_etablissementmode_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissementmode',
            name='recommande',
            field=models.BooleanField(default=False, help_text='Un seul mode peut être recommandé par établissement.', verbose_name='Recommandé'),
        ),
    ]
