# Generated by Django 5.2.14 on 2026-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_etablissementmode_recommande'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelavage',
            name='consigne_securite',
            field=models.TextField(blank=True, default='', help_text='Ex. videz les poches, retirez le sable, etc.', verbose_name='Consigne de sécurité'),
        ),
        migrations.AddField(
            model_name='modelavage',
            name='textiles_interdits',
            field=models.JSONField(blank=True, default=list, help_text='Liste des textiles déconseillés pour ce cycle.', verbose_name='Textiles à éviter / interdits'),
        ),
        migrations.AlterField(
            model_name='modelavage',
            name='message_guide',
            field=models.TextField(blank=True, default='', verbose_name='Pourquoi choisir ce mode (bénéfice client)'),
        ),
    ]
